version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
  api:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/stockpilot
      - PORT=4000
      - JWT_ACCESS_SECRET=change_me
      - JWT_REFRESH_SECRET=change_me_refresh
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongo
volumes:
  mongo-data:
